---
# +operator-builder:resource:collectionField=cloudProvider,value="aws",include
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-aws
  namespace: nginx-ingress  # +operator-builder:field:name=namespace,default="ingress-system",type=string
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
---
# +operator-builder:resource:collectionField=cloudProvider,value="gcp",include
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-gcp
  namespace: nginx-ingress  # +operator-builder:field:name=namespace,default="ingress-system",type=string
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
---
# +operator-builder:resource:collectionField=cloudProvider,value="azure",include
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-azure
  namespace: nginx-ingress  # +operator-builder:field:name=namespace,default="ingress-system",type=string
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
---
# +operator-builder:resource:collectionField=cloudProvider,value="none",include
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-no-provider
  namespace: nginx-ingress  # +operator-builder:field:name=namespace,default="ingress-system",type=string
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress

