---
name: Run E2E Test
description: Run E2E Test

inputs:
  codebase-artifact:
    description: Codebase Artifact to Download
    required: true

runs:
  using: composite
  steps:
    - name: Download Necessary Artifacts
      shell: bash
      run: |
        # setup kind
        if [ -z $(which kind) ]; then
          echo "kind executable not found...installing"
          curl https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 -o /usr/local/bin/kind -L
          chmod +x /usr/local/bin/kind
        else
          echo "found kind executable at $(which kind)...not installing"
        fi

        # setup kubectl
        if [ -z $(which kubectl) ]; then
          curl -LO https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl
        else
          echo "found kubectl executable at $(which kubectl)...not installing"
        fi
      env:
        KIND_VERSION: v0.22.0
        KUBECTL_VERSION: v1.29.3

    - name: Setup KIND Cluster
      shell: bash
      run: kind create cluster --name operator-builder-test --config test/cases/default/kind-config.yaml

    - name: Install Custom Resources
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: |
        make controller-gen && make kustomize
        chmod +x bin/*
        make install

    - name: Build Container
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: IMG=localhost:5000/${{ inputs.codebase-artifact }}:latest make docker-build

    - name: Push Container
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: IMG=localhost:5000/${{ inputs.codebase-artifact }}:latest make docker-push

    - name: Sideload Docker Image for KIND
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: kind load docker-image --name operator-builder-test localhost:5000/${{ inputs.codebase-artifact }}:latest

    # TODO: this would be much easier with yot and is extremely ugly with default kustomize files
    - name: Set Image Pull Policy to IfNotPresent
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: |
        sed -i '/image\: controller\:latest/a\'$'\n''        imagePullPolicy\: IfNotPresent' config/manager/manager.yaml

    - name: Deploy Operator
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: IMG=localhost:5000/${{ inputs.codebase-artifact }}:latest make deploy

    - name: Run E2E Tests
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: |
        # TODO: this is temporary to ensure we test the reconciliation loop
        # for our test workloads.  the end goal would be to genericize this
        # to ensure we can test any workload.
        if [[ -f .workloadConfig/apps_v1alpha1_webstore_test.go.test ]]; then
          cp .workloadConfig/apps_v1alpha1_webstore_test.go.test test/e2e/apps_v1alpha1_webstore_test.go
        fi

        # run the e2e tests
        DEPLOY_IN_CLUSTER="true" make test-e2e

    # TODO: this is a stub until this action is fixed.  currently, the make
    # targets are inconsistently missing.
    # - name: Install Documentation
    #   shell: bash
    #   working-directory: /tmp/operator-builder-test
    #   run: make docs

    - name: Undeploy Operator
      shell: bash
      working-directory: /tmp/operator-builder-test
      run: make undeploy
