---
name: Docs
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-material-extensions mike
      - run: mkdocs gh-deploy --force

